version: '3'
services:
  backend:
    build: ./To-Do-List/backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/myapp

  frontend:
    build: ./To-Do-List/forntend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
